# read堵塞先改100 update_rate
controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false

    gm6020_control:
      type: gm6020_controller_pkg/GM6020Controller
    
    joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

gm6020_control:
  ros__parameters:
    update_rate: 100